### ISSUE TITLE
Can you describe what the contest goals are? The link to the contest site is down.

### ISSUE THREAD

**Issue by zlccccc** [KevinZeng08/sigmod-2024-contest#1]
可以介绍一下竞赛目标是啥么？竞赛网站链接挂了

**Comment by KevinZeng08** [comment]
Hi. This contest gives a set of entries, each entry consists of one vector and several attributes, divided into the base dataset for indexing and query dataset for query. We need to query the Top-K entries in the base dataset with each query entry, by minimizing the distance between vectors and matching the attributes of the base entries (i.e. hybrid vector search).  The goal is to achieve the highest recall of the query dataset within the specified time (20 minutes).
